# yml or properties can be both used to configure, format

# change the serve.port server.port=9090, not 8080
server:
  port: 9090

# set database driver
spring:
  datasource:
    # the same as the url in myEclipse
    # The URL syntax format is as follows
    # jdbc:mysql: is the fixed format, localhost is your hostname, 3306 is the default MySQL port number
    # serverTimezone=UTC specifies the time zone to the universal time
    # useUnicode=true specifies whether to use the Unicode character set and assigns the value to true
    # characterEncoding=utf-8 specifies the characterEncoding format to UTF8
    # need to change the hostname when using cloud server
    # my local database name : mydb
    #    url: jdbc:mysql://127.0.0.1:3306/mydb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://47.93.52.23:3306/storage?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 073cc347a629822d
    driver-class-name: com.mysql.cj.jdbc.Driver
  # springboot @JsonFormat 得到时分秒为00:00:00 解决办法
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# mybatis
